### ISSUE TITLE
Incomplete install of Visual Studio Code on Ubuntu 15.04

### ISSUE THREAD

**Issue by beruic** [ubuntu/ubuntu-make#112]
I have tried to install Visual Studio Code on Ubuntu 15.04 with `umake web visual-studio-code`. The install seems to go through fine, and the files are there, but no menu entry is created, and when I try to run the `Code` executable from terminal I get the following message:

    ./tools/web/visual-studio-code/VSCode-linux-ia32/Code: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by didrocks** [comment]
Interesting, so visual studio code has a dependency on gtk 2.0. I guess your install didn't have it.

Ok, so, to fix your immediate problem, just install libgtk2.0-0. I'll add that with the next release next week.
Thanks for your contribution :)

**Comment by beruic** [comment]
Well, that library was already installed.

I also tried to run `locate libgtk-x11-2.0.so.0` and the file was found at this location: `/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0`

After finishing the installation, there's also no menu entry for Visual Studio Code, and trying to remove it by issuing `umake web -r visual-studio-code` just returns

    ERROR: You can't remove Visual Studio Code as it isn't installed

**Comment by beruic** [comment]
Might the issue be that I run 64-bit Ubuntu and umake installs a 32 bit version?

I just noticed that the folder installed by umake is `~/tools/web/visual-studio-code/VSCode-linux-ia32`, and when I download the 64 bit version from https://code.visualstudio.com/ (that works btw), it unpacks a folder named `VSCode-linux-x64`.

**Comment by didrocks** [comment]
Seems clearly to be a multi-arch issue.
It seems that visual studio code is now available on 32 bits, which wasn't the case before (there were only a 64 bits version), and they changed the link to fallback to the 32 bits with the old one.

So yeah, your system expect the 32 bits of  libgtk-x11-2.0.so.0 (which you can install on your 64 bits machines), hence the message.

I need to change the visual studio code to now supports the 32 bits and ensure that on 64 bits, it downloads the 64 bits version. Thanks for the feedback, will fix that shortly! :)

**Comment by beruic** [comment]
Will taht fix the missing menu entries as well?

**Comment by didrocks** [comment]
Right, I guess they changed their zip file layout (I see that I have a test failing due to this), I'm jumping on it tomorrow morning and will keep you posted.

**Comment by didrocks** [comment]
* Ok, got it all fixed now. I confirm the download page parsing changed, and they fallbacked to i386 now (which wasn't supported on release day). That's why the wrong version was downloaded for you.
* The archive content changed as well, and so, links to the icon and executable path were broken due to this (and so, missing menu entries).
* Due to those paths changes, ubuntu make thought that you didn't install it (as having the whole archive content is a condition to detect if a framework is fully installed or not).

Note that the tests confirm all this, I just needed to refresh them for the new layout
0.8.2 is currently building on the builders and should be published soon, thanks again for your feedback and sorry for the trouble! ;)

**Comment by medmo7** [comment]
I have a similar issue here . can you give me the command to install the 32bit as I'm a novice in ubuntu.
Thanks.
