### ISSUE TITLE
umake android wrong icon path 

### ISSUE THREAD

**Issue by zob** [ubuntu/ubuntu-make#115]
The launcher file the is created in ~/.local/share/applications/android-studio.desktop has the Icon= pointing to a wrong filename.
I corrected it earlier today. I don't quite recall what the wrong filename was maybe ~/tools/android/android-studio/bin/intellij.png
Should be changed to:
Icon=~/tools/android/android-studio/bin/studio.png

Or else we just get the ugly question mark default icon.

**Comment by didrocks** [comment]
Thanks for reporting this bug on Ubuntu make and help making it better!

What version of Ubuntu Make you are using? This bug is already fixed in Ubuntu Make 0.8 (https://launchpad.net/ubuntu/+source/ubuntu-make/0.8).

Ensure to always get the latest version (some of those fixes can't be SRUed in the official distribution) in the official Ubuntu Make ppa for your Ubuntu version at https://launchpad.net/~ubuntu-desktop/+archive/ubuntu/ubuntu-make.
Keep me posted if the issue was just that you were not current ;)
Thanks again, and do not hesitate to report further bugs ;)
