### ISSUE TITLE
Development friendly Dockerfile

### ISSUE THREAD

**Issue by syndbg** [ubuntu/ubuntu-make#116]
This is an enhancement.

The current Dockerfile is installing *some* of the requirements for development.

If we want to have an easy to use Docker image for developers to just build and run, it requires a few changes.

* Adding git
* Cloning the latest repo from github
* Installing the Python requirements from requirements.txt
* Linking the umake bin.

I will submit a PR for this issue.

**Comment by didrocks** [comment]
Hi! Thanks for your PR and suggestion!
However, there is a small misunderstanding on what the docker file is for: it's not for developers (you will notice, it's not shipped in the packaged version), but for testing.

We test all medium tests in isolation of a real system, with fake packages and fake web server. That way, we control the environment and can know if one regression is due to a 3rd party or us.

Does it make more sense? Sorry for the misunderstanding (maybe you want to add a comment for this in the DockerFile?)
If you are interested, you can find more information here: http://blog.didrocks.fr/post/Ubuntu-Developer-Tools-Center%3A-how-do-we-run-tests

However, if you want to contribute to ubuntu make, there are a lot of opportunities in opened whislist bugs on that project!
Thanks!

**Comment by syndbg** [comment]
I will definitely look in the other issues.
However are there any plans to have a separate developers Dockerfile?

**Comment by didrocks** [comment]
As already told on other threads, just back from long holidays, so catching up and sorry for the long answer :)

This is of course is possible, however, I don't really know what would be the advantage? I guess the virtualenv help to develop Ubuntu Make, I don't know how producing a get ready version of a Docker image for this would go into that direction? I'm probably just missing something obvious, please enlight me :)
