### ISSUE TITLE
Idea: use docker to build containers of different dev stacks

### ISSUE THREAD

**Issue by owais** [ubuntu/ubuntu-make#13]
I work on multiple projects at a time. udtc should allow me to generate a number of environments for a django project so I can isolate my different projects. I can also work on a rails app at the same time. Add some Golang projects. Run postgresql, oracle or mysql only when needed, etc etc. All this while keeping the base Ubuntu install very clean.

I'm willing to help with whatever time I can spare. udtc sounds really cool.

**Comment by hepin** [comment]
I think how about take a look at linuxbrew?

**Comment by techdragon** [comment]
I'd be leaning away from adding docker as a dependency where we may be able to accomplish everything we want without it. If I want a dev stack in a docker container... docker has its own tools for building that for me. Why does ubuntu make need to get involved in this?

**Comment by didrocks** [comment]
Because it will deliver you a tested and central recipe of a whole stack based on the 500 tests we have. It's also just one command line tool to install multiple frameworks, so same interface, always delivering latest and tested upstream goodness, with all the small steps that you don't necessarily have to hunt down on the web.
