### ISSUE TITLE
Adding Netbeans SE IDE support problems

### ISSUE THREAD

**Issue by fcole90** [ubuntu/ubuntu-make#139]
I'm trying to add support to Netbeans IDE, but I have some problem to get started working on it. Is there some more documentation with the APIs of ubuntu-make?
The problem is that as far as I see, most of the IDEs are in tar.gz, while Netbeans requires to run it's installer.sh and follow its wizard.

A simple way to install it would be to:
-verify requirements ( (jdk-7 || jdk-8) && jayatana) possibly add in the future an option to download the oracle java + netbeans and to chose among java versions
wget "http://download.netbeans.org/netbeans/8.0.2/final/bundles/netbeans-8.0.2-javase-linux.sh"
chmod +x netbeans-8.0.2-javase-linux.sh
./netbeans-8.0.2-javase-linux.sh

Icons, netbeans.desktop, licence accepting and other configs are run inside the wizard.

The problem is that I don't know how to do that inside ubuntu-make, some API documentation would be very useful

**Comment by didrocks** [comment]
Hey, thanks for looking into this!

The support for executing shell script during the installation process is on purpose: we do prefer unpacking a prepared binary. Indeed, running scripts like that during an installation for things not coming from the archive can violate the ubuntu policy. Do you think we can find a prepared tar that can be just unpacked instead of running that shell script?

**Comment by fcole90** [comment]
Thanks for the fast answer. I've searched deeper and found this [1] page, seems right what we needed, now I just need to figure which to use for ubuntu-make. This [2] seems the "vanilla" one, without other plugins, will it be better to use that or the one that ships with Java SE support plugins? (Any plugin can be installed after from the IDE itself, like you do on Eclipse).

[1]: http://download.netbeans.org/netbeans/8.0.2/final/zip/netbeans-8.0.2-201411181905.zip
[2]:http://download.netbeans.org/netbeans/8.0.2/final/zip/netbeans-8.0.2-201411181905.zip

**Comment by fcole90** [comment]
I'm checking the package, seems that the License confirmation is asked the first time the IDE is executed, is it a problem?

**Comment by didrocks** [comment]
Thanks for checking! yeah, 1 and 2 looks like exactly what is needed. Is there any webpage that can be scrapped to get those urls (that's how we do in most frameworks)?

On the preferred one to choose, we can have both, like "netbean" and "netbean-java" options, this doesn't sound like crazy to me :)

Having the License confirmation asked the first time the IDE is executed rather than on installation time is fine as well. So you need to adapt the existing code to not ask for license (which is just an option in __init__().

So, unfortunately, we don't have any documentation on the API. However, most of contributors survived quite well to it taking different existing examples, and I'm here to help! (Especially on the testing side :)).

What you need to look for is first at umake/fameworks/
Most of the frameworks inherits from BaseInstaller which is doing basically all the dirty works. Then, there are hook or overrides in your framework to do what you want.
Android is the most straightforward one. Some in ide.py are more custom (as not scrapping the url or using BeautifulSoup), you can get some inspiration from them as well.

Do not hesitate if you have any other questions!

**Comment by fcole90** [comment]
Thanks, I will try and let you know!

**Comment by fcole90** [comment]
I think this is the page that we can parse ;)

**Comment by didrocks** [comment]
url missing? :)

**Comment by fcole90** [comment]
Sorry: https://netbeans.org/downloads/zip.html

**Comment by didrocks** [comment]
Sounds like exactly what we want! (so maybe try with the vanilla first, then we can add the cpp/java/php flavors?)

**Comment by fcole90** [comment]
Yes, that's the same I was thinking to do :smile:

**Comment by fcole90** [comment]
Sorry, new problem, BeautifulSoup seems to work well parsing the page, but the Netbeans download page is rendered at runtime by javascript code (which itself seem to be runtime loaded from one js function at the beginning) of the page. So I should load that script, run it to load the necessary function to load the zips. I'm working on it..

**Comment by fcole90** [comment]
I think this [1] will do the job. It's the js file mentioned before.

[1]: https://netbeans.org/images_www/v6/download/8.0.2/js/files.js

**Comment by fcole90** [comment]
Some initial work: https://github.com/fcole90/ubuntu-make/commit/b94f703a0ec266857f2ea4b31f2475d4ebd00949

**Comment by fcole90** [comment]
https://github.com/fcole90/ubuntu-make/commit/1cf2c1fcd20bd7ba2e834f3ad0dd9ce768689544?diff=unified

**Comment by didrocks** [comment]
mind sending a pull request? That will be easier for both of us to iterate over it :)

**Comment by fcole90** [comment]
Ok, I will ;) Can you help me understand how to register the netbeans ide (i.e. how to make '''umake ide netbeans''' to install netbeans)?

**Comment by fcole90** [comment]
Solved, I had one abstract method in the class :laughing:
