### ISSUE TITLE
ubuntu make does not work behind my proxy...

### ISSUE THREAD

**Issue by mbrotz** [ubuntu/ubuntu-make#156]
After setting the systemwide proxy settings and exporting the proxy env variables http_proxy="..." and https_proxy="...", the command umake ide eclipse fails with the following error message:

ERROR: hostname 'proxyhostname' doesn't match either of '*.eclipse.org', 'eclipse.org'

Installing ubuntu make with "sudo apt-get install ubuntu-make" worked fine. Everything else works with my proxy settings.

**Comment by didrocks** [comment]
Sorry for this issue, this is due to the newer version of python 3.4.3 in ubuntu 14.04 that was released a couple of weeks ago. The maintainers are pinged and we are discussing a resolution about it on https://bugs.launchpad.net/ubuntu/+source/python3.4/+bug/1500768.

A workaround is to use latest python-requests from my ppa if you are willing to install from it (available at https://launchpad.net/~didrocks/+archive/ubuntu/ppa/) or wait for the issue to be fixed in distro.

I'm closing this bug as invalid, but do not hesitate to comment on the launchpad bug to +1 the issue :)
Thanks again, and sorry for the bother!
