### ISSUE TITLE
umake --version Error

### ISSUE THREAD

**Issue by jravetch** [ubuntu/ubuntu-make#173]
When running umake --version with the latest ppa 15.11~trusty1, I get the following:

$ umake --version                                                                                                                      
Traceback (most recent call last):
  File "/usr/bin/umake", line 9, in <module>
    load_entry_point('Ubuntu-Make==0.0.1', 'console_scripts', 'umake')()
  File "/usr/lib/python3/dist-packages/umake/__init__.py", line 115, in main
    cli.main(parser)
  File "/usr/lib/python3/dist-packages/umake/ui/cli/__init__.py", line 174, in main
    print(get_version())
  File "/usr/lib/python3/dist-packages/umake/settings.py", line 34, in get_version
    version = open(os.path.join(os.path.dirname(__file__), 'version'), 'r', encoding='utf-8').read().strip()
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/umake/version'

**Comment by didrocks** [comment]
Hey! Thanks for reporting this bug!

Yeah, I know, I started to notice it thanks to your tests running against the system installed version: https://jenkins.qa.ubuntu.com/job/udtc-trusty-tests/label=ps-trusty-desktop-amd64-1,type=large/lastCompletedBuild/testReport/tests.large.test_basics_cli/BasicCLI/test_version/

I fixed it yesterday already, and just pushed the commit this morning https://github.com/ubuntu/ubuntu-make/commit/581904cbb3f69a3d96be3e7af60c8dca739b78b0
As the file hasn't a .py suffix, setup.py happily ignored it during install ;) (that's why I always emphase that the system tests are running against *installed* binaries instead of a checkouted file system) ;)

Let's see the positive side: I used that opportunity to stamp the generated umake binary with the correct version (not more 0.0.1 hardcoded), even if this info isn't surfaced anywhere to the user: https://github.com/ubuntu/ubuntu-make/commit/c8d0a154e123d4073bd7318c24c62e32668aafb1.

Thanks for reporting it and trying the new version! :-)
