### ISSUE TITLE
Go env variables not set properly in zsh

### ISSUE THREAD

**Issue by jravetch** [ubuntu/ubuntu-make#176]
When installing go, the following are added to .zprofile

```bash
# Ubuntu make installation of Go Lang
export GOROOT=/home/jravetch/.local/share/umake/go/go-lang:$GOROOT
PATH=/home/jravetch/.local/share/umake/go/go-lang/bin:$PATH
```

The second $GOROOT shouldn't be added.  It should look like:

```bash
export GOROOT=/home/jravetch/.local/share/umake/go/go-lang
```

Also GOPATH should be set to get, build and install packages outside the standard Go tree.

```bash
export GOPATH=/home/jravetch/.local/share/umake/go/go-lang

**Comment by didrocks** [comment]
Hey @jravetch:
on GOROOT, you are fully right, mind sending a PR my way?

on GOPATH, absolutly not. You set GOPATH to the current worskpace your are working in. The go installation path shouldn't be a workspace as you are mixing then binaries from Go and your own compiled or downloaded libs code.
The decision was then to not set GOPATH to any directory and let the user doing it in their own workspace as we don't know what directory they would use.

**Comment by jravetch** [comment]
@didrocks re GOROOT, i tried a few things but still the same result.  Is it an issue with add_env_to_user?

re GOPATH understood and agreed

**Comment by didrocks** [comment]
that's the default behavior if this function (if it's set already for your user, otherwise, we don't do it). However, there is a way to say "please really override this value" via setting keep=False. You can see an example of it in the unit tests:
tests/small/test_tools.py, function test_add_env_to_user_not_keep().
You have other examples in umake/frameworks/android.py

(tests are usually a great way to discover the API) But in that case, the docstring of add_env_to_user() should be clear as well, no?

**Comment by jravetch** [comment]
@didrocks Cool thanks, I figured it out #177 will fix it.

**Comment by jravetch** [comment]
@didrocks Ok, #178 is now clean and ready for review.

**Comment by didrocks** [comment]
Closing as merged now. Many thanks again!
