### ISSUE TITLE
I can't install unity3d

### ISSUE THREAD

**Issue by dikel** [ubuntu/ubuntu-make#193]
When I try to install unity3d I get:

ERROR: Package requirements can't be met: installArchives() failed
Subprocess output: E:Reverse conflicts early remove for package 'libglapi-mesa:amd64' failed

What to do?

**Comment by didrocks** [comment]
hey, thanks for trying Ubuntu Make and help to make it better!
I think unfortunately this has nothing to do with Ubuntu Make itself, but you have some ppas or packages installed on your system that conflicts with the packages needed for Unity 3D.

The best way to debug this is to use apt directly. You can `apt-get` the list of packages that Ubuntu Make is trying to install so that Unity 3D can run. You can have that list in https://github.com/ubuntu/ubuntu-make/blob/master/umake/frameworks/games.py#L124.

I guess your conflict is between *libgl1-mesa-glx*, *libglu1-mesa* which are required for Unity 3D and *libglapi-mesa* that you already installed and can't be removed by apt.

**Comment by dikel** [comment]
I've tried to install libgl1-mesa-glx but I get:

The following packages have unmet dependencies:
 unity-control-center : Depends: libcheese-gtk23 (>= 3.4.0) but it is not going to be installed
                        Depends: libcheese7 (>= 3.0.1) but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

I have just installed Ubuntu and I haven't install almost anything in it.

**Comment by didrocks** [comment]
Your dependency issue (unity-control-center getting libcheese-gtk23) is not related at all to Ubuntu Make or libgl1-mesa-glx.

It means that your distribution had something weird happening during install or recently: you package system has been broken.
I suggest to get some live support on IRC (freenode): #ubuntu where people will be able to help you, that will be easier than through bug comments. More information on how to connect is available at http://community.ubuntu.com/contribute/support/irc/.

I hope you will be able to fix this issue!
