### ISSUE TITLE
OpenSSL Error running umake  go

### ISSUE THREAD

**Issue by johnturek** [ubuntu/ubuntu-make#195]
While attempting to install Go  via Umake ----

jturek@jturek-MacBookAir:~$ umake go
Choose installation path: /home/jturek/tools/go/go-lang
Downloading and installing requirements                                        |
ERROR: https://storage.googleapis.com/golang/go1.5.1.linux-amd64.tar.gz couldn't finish download: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1749)
100% |#########################################################################|
ERROR: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1749)

**Comment by didrocks** [comment]
Hey,

Thanks for reporting this bug and help Ubuntu Make to get better.
It really seems to be a valid error, like a https/ssl certificate being invalid. Did you retry it later on, is your browser shoing up the green lock (telling that https is fully served under web site having a valid certificate)?

**Comment by didrocks** [comment]
Closing for now as no update. Do not hesitate to reopen it if that's still an issue for you!

**Comment by isatori** [comment]
Hi didrocks,

Please reopen as I also encountered it on a different command `$ umake ide idea-ultimate`, here's the log:

Downloading and installing requirements
INFO: Start downloading DownloadItem(url='https://download.jetbrains.com/idea/ideaIU-2016.3.3.tar.gz', checksum=Checksum(checksum_type=<ChecksumType.sha256: 'sha256'>, checksum_value='95871c9a8aed1bd8992ff493fbc5fc31674b18ef3cd509eb8f2e5650b3419eaf'), headers=None, ignore_encoding=True, cookies=None) to a temp file
INFO: Starting new HTTPS connection (1): download.jetbrains.com
INFO: Starting new HTTPS connection (1): download-cf.jetbrains.com
ERROR: https://download.jetbrains.com/idea/ideaIU-2016.3.3.tar.gz couldn't finish download: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1977)
INFO: All pending downloads for [DownloadItem(url='https://download.jetbrains.com/idea/ideaIU-2016.3.3.tar.gz', checksum=Checksum(checksum_type=<ChecksumType.sha256: 'sha256'>, checksum_value='95871c9a8aed1bd8992ff493fbc5fc31674b18ef3cd509eb8f2e5650b3419eaf'), headers=None, ignore_encoding=True, cookies=None)] done
100% |########################################################################|
ERROR: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1977)

I believe that ubuntu make downloads in different URL's and then combine it or something which make sense because the checksum are the same, but somehow it cannot merge the two.  I managed to download the IDE with the first URL with no errors on a firefox browser, but the ubuntu make doesn't allow you to use the downloaded *.tar.gz as an alternative solution.

Regards
