### ISSUE TITLE
Provide an 'update' command or change the wording of install

### ISSUE THREAD

**Issue by fishgills** [ubuntu/ubuntu-make#208]
Every few weeks, there's a new version of Idea.

It seems a little clunky to be using `umake ide idea-ultimate` and have it prompt me to "reinstall".

This is probably incredibly small but just changing that reinstall message to say something about "upgrade" would make it a little better experience. ;)

**Comment by techdragon** [comment]
I wasted far more time than I should have trying to work this out before heading for the bug tracker and finding this issue. 

Add an update command. Its really needed.

**Comment by didrocks** [comment]
Thanks for your bug report and feedback on this!

Reinstall isn't really an upgrade/update per self, as you are just swapping out and in a new installation. We rely most of the time on the tool having its own upgrade mechanism (that's the safer bet) and I though ide had some of them?

That's the reason why `umake ide idea-ultimate` prompt for reinstall, because it is a reinstallation (it's removing the previous one, add a new one, hoping that the IDE can pick old previous configuration file). There is more rationale on bug #74, I'm closing this one to keep the discussion in a single place. Your feedback there would be really welcome.
