### ISSUE TITLE
Feature Request: Allow user to specify alternate file location on "Can't parse the download URL" error

### ISSUE THREAD

**Issue by Axoren** [ubuntu/ubuntu-make#221]
In regards to this error: https://github.com/ubuntu/ubuntu-make/issues/220 (which seems to be a recurring issue whenever JetBrains changes their site) 

I've downloaded the tar.gz myself since umake has failed to download it. Since it has failed to parse the URL, it will not proceed with actually setting up the environment and everything else that it does.

If the only thing missing is that it needs the tar.gz, add a Plan B option flag.

**Comment by didrocks** [comment]
Thanks for proposing this! It's a nice suggestion, but I'm a little bit hesitant of providing such a mode. Basically, that will throw out all the tested environment that we do on the server side to ensure what you are getting is what to expect. Basically, there are multiple things that could have changed:

- first, getting the user to get the correct link, if you look at similar bug (that are closed) of bug #220, people suggest a new download page, not the download link directly, and of course, Ubuntu Make will know nothing about the new download page structure, this will be only useful with the download link, which can be hard to get with client-side templating even for people trying to download!
- secondly, most of website changes are coming with a new version, this one can require new dependencies which will then not be installed, so leading to less than an ideal situation
- same as well with code path which can change, and so, the generated desktop files and various integrations (adding people to particular group, change environment variables) may not match this new version we don't know of.

That's the reasoning why I think it's not as straightforward and giving a way for people to download to tell "you may download some hundreds of megabytes, but we can't assure the result will work" isn't the kind of experience which is really good IMHO.

Any idea on that topic?

On the contrary, when a webpage changes, we know about it really quickly (see that #220 was fixed on the 11th for instance). However, like you did, we received quite a number of bug reports even once fixed and released. I guess that's because, as we want to be fast on delivering a fix and not relying on the SRU process, we deliver it through our PPA that most of people don't have enable when installing on latest devel version. One way would be to change the message telling "did you try latest ubuntu-make version available in <ppa_address>"? Would that make sense to you?

**Comment by Tinche** [comment]
Another idea might be separating out recipes for tools from the main installation, and having the installation fetch them periodically. I seem to remember a similar piece of software handling it this way (Crossover or PlayOnLinux)?

Then in the case of parse failure, umake could automatically check if there's a newer recipe and retry that. (Also if that fails, check if a bug has already been filed, like Atom does.)

**Comment by didrocks** [comment]
Yeah, I've thought about this as well. However, a server/client architecture right away is another piece of work. I still see the long time direction of ubuntu make to be to download server-side prepared containers, running the tests there and once validated, publishing this piece ready for consumption. That will remove this issue as well then in addition to other advantages.
