### ISSUE TITLE
Error installing unity3d

### ISSUE THREAD

**Issue by Alvarz** [ubuntu/ubuntu-make#253]
I guys, keep doing the great job!

I got a fresh install of ubuntu  14.04.3 and when I try to install unity3d throught umake, it gave that error:

'ERROR: installArchives() failed
Subprocess output: E:Reverse conflicts early remove for package 'libglapi-mesa:amd64' failed'

then I went to synaptic to see whats going on and I could notice I had installed  libglapi-mesa-lts-virvid:amd64. 

I made a search about it and ubuntu 14.04.3 ship with libglapi-mesa-lts-virvid:amd64 so it's there by default, in any case if I try to force uninstall it and then install libglapi-mesa:amd64,it try to delete my whole system, even ubuntu.desktop.

What can I do?

**Comment by LyzardKing** [comment]
This has to do with the lts-enablement stack. Updated versions of mesa that are added with a different name (ex libglapi-mesa-lts-vivid, or libglapi-mesa-lts-wily).
I think we can add them as possible dependencies. On non lts it should find the normal version.

**Comment by Alvarz** [comment]
Thanks for the reply!!

So should I wait for the next update or should I install it throught the deb package on unity3d website?

**Comment by didrocks** [comment]
It's looking good to me. However, I'll appreciate as well testing from someone on 14.04. @LyzardKing: do you mind running the testssuite in xenial, wily and trusty?
`./runtests vm <your_general_test_command>`. It should tell/yell at you and indicate how to build the vm when needed! Tell me if that doesn't work for you ;)

@Alvarz: do you mind using that branch? It's pretty easy (install git first! ;)), just:
```
git clone https://github.com/LyzardKing/ubuntu-make
cd ubuntu-make
git checkout unity-3d_lts_mesa
bin/umake games unity3d
```
That way, you have access on that branch to the latest code and can keep us posted if your issue is fixed that way! Thanks ;)

**Comment by Alvarz** [comment]
@didrocks  yeah I would love to help on this project. 
Should I first uninstall my umake to test this branch?

**Comment by LyzardKing** [comment]
No need to uninstall. if you follow the commands in the previous comment you're good to go

**Comment by LyzardKing** [comment]
@didrocks The ./runtests vm test.. returns "adt-run isn't installed.".
Am I missing something obvious? (Might be :))

**Comment by LyzardKing** [comment]
@didrocks I figured out what was missing, I needed some packages on my system.
I'll let you know if I get somewhere.
@Alvarz If you need help testing let me know!

**Comment by Alvarz** [comment]
Hello guys, sorry for the delay on the test.

I've made it and sadly the result it's the same......

Here is what my terminal show



```
carlos@carlos-desktop:~/Descargas/testUmake/ubuntu-make$ git checkout unity-3d_lts_mesa
Branch unity-3d_lts_mesa set up to track remote branch unity-3d_lts_mesa from origin.
Switched to a new branch 'unity-3d_lts_mesa'
carlos@carlos-desktop:~/Descargas/testUmake/ubuntu-make$ bin/umake games unity3d
Choose installation path: /home/carlos/.local/share/umake/games/unity3d
Downloading and installing requirements                                        |
ERROR: installArchives() failed
Subprocess output: E:Reverse conflicts early remove for package 'libglapi-mesa:amd64' failed
```
How can I help??

**Comment by LyzardKing** [comment]
@Alvarz Do you have the -lts- version of libglu1-mesa as well?

**Comment by Alvarz** [comment]
@LyzardKing No I don't, I have `libglu1-mesa` and `libglu1-mesa-dev`

**Comment by mateushonorato** [comment]
I have the same problem here. Using Linux Mint 17.3 Cinnamon.

**Comment by LyzardKing** [comment]
I have a version that should work. I haven't merged it yet since I'd like to test it on different virtual machines. I haven't had the time yet.
If you want to try it out you can do:
`git clone https://github.com/LyzardKing/ubuntu-make`
`cd ubuntu-make`
`git checkout unity-3d_lts_mesa`
`bin/umake games unity3d`

Could you tell me what system you have?

I'll see if I can finish the testing today.

**Comment by LyzardKing** [comment]
@mateushonorato Fixed now. 
You can get the latest version from github, or the next release
