### ISSUE TITLE
ubuntu16.04 can't swap ctrl and Caps Lock 

### ISSUE THREAD

**Issue by chenyangguang** [ubuntu/ubuntu-make#319]
i was puzzle  that it was always failed swap ctrl and Caps Lock in ubuntu16.04. It's fine in ubuntu14.04. My way is: 
1) sudo apt-get install gnome-tweak-tool,
2) running the gnome-tweak-tool command,
3) select 'Typing' option on the left, then choose 'Ctrl key position', choose 'Swap Ctrl and Caps Lock'.
4) reboot my computer.
Ctrl is  still Ctrl, Caps Lock still Caps Lock. So oddly. Maybe any one has the similar hesitation?

**Comment by didrocks** [comment]
Hum, thanks for your bug report, but I think you should target it against the right project. Ubuntu Make isn't gnome-tweak-tool :)

Please report your bug here: https://bugs.launchpad.net/ubuntu/+source/gnome-tweak-tool/+filebug which is the correct ubuntu project for this :)

Closing this bug report then!
