### ISSUE TITLE
Firefox Developer Edition not installable: ERROR: Download page changed its syntax or is not parsable

### ISSUE THREAD

**Issue by gerdneuman** [ubuntu/ubuntu-make#341]
I wanted to install in a VirtualBox Ubuntu 16.04 image. Does not work:

```
osboxes@osboxes:~$ umake web firefox-dev
Choose installation path: /home/osboxes/.local/share/umake/web/firefox-dev
ERROR: Download page changed its syntax or is not parsable
```

**Comment by oijazsh** [comment]
Should be easily fixed by changing the regular expression over [here](https://github.com/ubuntu/ubuntu-make/blob/master/umake/frameworks/web.py#L83) to be less dependant on context, e.g.

```python
reg_expression = r'href="(\S+os=linux{}&amp;lang=\S+)"'.format(tag_machine)
```

The original broke due to additional newlines in the page source. Large tests should pass with the new one.

I run into the same issue as #318 when running tests so it'll be nice if someone else could make this fix.

**Comment by nickpushnikov** [comment]
I' m sorry. But what i should do with this code?  reg_expression = r'href="(\S+os=linux{}&amp;lang=\S+)"'.format(tag_machine). Feel stupid, but i just came to linux

**Comment by NoellyB76** [comment]
You need to upgrade ubuntu-make (umake) to get this solved. The sources that come with "out of the box" Ubuntu (at least in my version of 16.04), are not using the latest ubuntu-make, and specifically are not using the version that contains the fix listed above.

So, to do that, first add the PPA for ubuntu-make, then the Ubuntu will update its list of upgradable packages after you run an apt update. Once you do that, then you can then run your umake install again.

Here's the commands I used:

$ sudo add-apt-repository ppa:ubuntu-desktop/ubuntu-make
$ sudo apt update


At this point, you should see that ubuntu-make is listed as a package with an upgrade available, or you can use this command to make sure that ubuntu-make is available for upgrade:

$ sudo apt list --upgradable

So, assuming you see something like the following, you should be all set to run the upgrade:

$ apt list --upgradable
>Listing... Done
>ubuntu-make/yakkety,yakkety 16.11.1~yakkety1 all [upgradable from: 16.05]
>N: There is 1 additional version. Please use the '-a' switch to see it

Enter the command to actually do the upgrade:

$ sudo apt upgrade

Once the upgrade has finished, use umake as you normally would. In the case of FF Aurora / Dev Edition:

$ umake web firefox-dev

**Comment by maddyBoy** [comment]
Just to add if some one dont now how to launch the firefox-dev  ( atleast i )

$ sudo ln -s ~/.local/share/umake/web/firefox-dev/firefox /usr/bin/firefox-dev ( make a symsymbolic link )
$ firefox-dev ( to launch from terminal)

**Comment by LyzardKing** [comment]
@maddyBoy umake already does this.
It links all executables to .local/share/umake/bin
and adds that to the path.
It's not recommended to add links manually, since umake cannot clean them

**Comment by maddyBoy** [comment]
@LyzardKing ok, so what should i do now as i did that manually?

**Comment by LyzardKing** [comment]
you can continue using your setup, but I wouldn't suggest it
If you need to reinstall/update I would remove your link, since we create our own
after you install via umake it should be available already.
If you run `echo $PATH` you should see /home/<username>/.local/share/umake/bin
andi in that folder a link to the firefox executable

**Comment by LyzardKing** [comment]
Ah...our link is named different..
it's `firefox-developer`
So in fact you can already use that!
