### ISSUE TITLE
Use plainbox for testing udtc itself

### ISSUE THREAD

**Issue by zyga** [ubuntu/ubuntu-make#38]
Hi.

I'm the lead developer of plainbox/checkbox - testing tools common to Ubuntu.

Our tools allow to express and run test definitions in a uniform way. Existing 'small/medium/large' tests could be defined as plainbox job definitions. Plainbox has a lot of nice features, including stable core, rich feature set (manual & automatic tests, reporting, handling root) and a nice touch UI (which also works on the desktop).

We're trying to move all ad-hoc testing intiatives to use plainbox and I'd like to explore udtc to use plainbox as well. I'm offering my help to teach everyone about how this can be done and to do a lot of the work myself.

As far as technical bits go, to run tests you'd need to get one more dependency (plainbox) which is available from pypi/debian/ubuntu.

**Comment by didrocks** [comment]
It seems that the plainbox team doesn't have time to work on this (since last year). We have a quite solid integration story around CI with Travis and jenkins. I'm closing this one for now. If the plainbox team has time and have added value for our Ubuntu Make CI tests, do not hesitate to reopen the bug! Thanks :)
