### ISSUE TITLE
PHPStorm icon missing

### ISSUE THREAD

**Issue by belaustegui** [ubuntu/ubuntu-make#409]
When installing PHPStorm with Ubuntu Make, the application icon is missing.

The installation command was:

```bash
umake ide phpstorm
```

The application works properly, but the icons are broken in the sidebar and in the application menu:
![application-menu](https://cloud.githubusercontent.com/assets/2965623/23094106/fa387c52-f5f2-11e6-8c79-2ce9a7f28ee0.png)
![sidebar-icon](https://cloud.githubusercontent.com/assets/2965623/23094107/fa3aa72a-f5f2-11e6-94e4-8d00afc9a928.png)

**Comment by didrocks** [comment]
Thanks for your bug report and help making ubuntu make better! This should now be fixed in the master branch and will be released later this month :)

You can use the version from master (git clone it), cd into the directory and just run `bin/umake` instead of `umake`. It will use the local version.
