### ISSUE TITLE
Question: How are apps installed via umake updated?

### ISSUE THREAD

**Issue by sahil48** [ubuntu/ubuntu-make#446]
Umake definitely works really well for installing the latest version of a program. What is the best way to handle updates to the program? Within the app using an app's built in updator? Through a package manager (I'm not even sure this is available)? By running umake again (What is the impact on preferences I changed in the last build)?

**Comment by LyzardKing** [comment]
There are many closed issues related to this.
The TLDR is:
If something has the ability to autoupdate (firefox-dev, intellij) they can be used to update as intended.
For the rest a reinstall (running umake again) is essentialy all you need to update.
The preferences are not touched, since the programs usually save them in .config, or .local in your HOME.

To see the other discussion threads:
https://github.com/ubuntu/ubuntu-make/issues/122
