### ISSUE TITLE
How to get Unity Launcher for Visual Studio Code and Atom to respect .bashrc

### ISSUE THREAD

**Issue by sahil48** [ubuntu/ubuntu-make#448]
I am using Ubuntu 16.04 in virtualbox. There is a bug in electron that causes visual studio code and atom to open with a blank screen with the gpu enabled. To stop this, instead of launching

`visual-studio-code` and `atom`

I need to launch the application as `visual-studio-code --disable-gpu` and `atom --disable-gpu`.

When I add aliases to the .bashrc file in my home directory,
~~~~~~~~~~
# Aliases for Visual Studio Code and Atom to disable gpu upon launch
alias visual-studio-code='visual-studio-code --disable-gpu'
alias atom='atom --disable-gpu'
~~~~~~~~~~

Visual Studio Code and Atom launch fine from the terminal. However, When I click the app icon, it still launches without disabling the gpu for the application. How do I address this?

**Comment by LyzardKing** [comment]
Since we have the symlink in PATH, we have to change the ide desktop generation functions
from Exec=<full path> to Exec=<command>

in the post_install method:
replace exec=self.exec_path, with exec=self.exec_link_name,

If you want to replace them all and test them it would be great, since I don't have that much time.
