### ISSUE TITLE
Add DBeaver support

### ISSUE THREAD

**Issue by patsevanton** [ubuntu/ubuntu-make#551]
Would it be possible to add support for DBeaver ?

DBeaver - Free multi-platform database tool for developers, SQL programmers, database administrators and analysts. Supports all popular databases: MySQL, PostgreSQL, MariaDB, SQLite, Oracle, DB2, SQL Server, Sybase, MS Access, Teradata, Firebird, Derby, etc.

https://dbeaver.io/download/
Linux have package:
Linux Debian package 64 bit (installer)
Linux Debian package 32 bit (installer)
Linux RPM package 64 bit (installer)
Linux RPM package 32 bit (installer)
Linux 64 bit (tar.gz archive)
Linux 32 bit (tar.gz archive)

**Comment by LyzardKing** [comment]
Sure! It seems like a nice way for a new contributor to start helping on Ubuntu Make.

**Comment by patsevanton** [comment]
Please write manual to will add package to ubuntu-make

**Comment by LyzardKing** [comment]
To add a framework you have to first find a similar framework.
I guess we could add this in ide.py
Also, I noticed that there's a github releases page, so you can use that to fetch the latest. 
Look at the atom ide (in umake/frameworks/ide.py) since it should be basically identical.
After the framework is setup you can add a mock of the website for the tests.
My advice is to have a look at the parts regarding atom in these files:
umake/frameworks/ide.py
tests/large/test_ide.py
tests/medium/test_ide.py

**Comment by akhil2015** [comment]
check this repo out https://github.com/dbeaver/dbeaver
