### ISSUE TITLE
Can not install Rust v1.26.1

### ISSUE THREAD

**Issue by tredoe** [ubuntu/ubuntu-make#557]
```
$ umake --version
16.11.1
$ umake -vv rust
#(cutting off noise)
DEBUG: Installation path provided. Checking if exists.
DEBUG: Download application provider page
INFO: Start downloading DownloadItem(url='https://www.rust-lang.org/en-US/downloads.html', checksum=None, headers=None, ignore_encoding=False, cookies=None) in memory
DEBUG: Starting new HTTPS connection (1): www.rust-lang.org
DEBUG: https://www.rust-lang.org:443 "GET /en-US/downloads.html HTTP/1.1" 200 91
DEBUG: Deliver download update: {'https://www.rust-lang.org/en-US/downloads.html': {'current': 0, 'size': 91}} of 91
DEBUG: Deliver download update: {'https://www.rust-lang.org/en-US/downloads.html': {'current': 91, 'size': 91}} of 91
INFO: https://www.rust-lang.org/en-US/downloads.html download finished
INFO: All pending downloads for [DownloadItem(url='https://www.rust-lang.org/en-US/downloads.html', checksum=None, headers=None, ignore_encoding=False, cookies=None)] done
DEBUG: Fetched download page, parsing.
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/rust.py", line 98, in get_metadata_and_check_license
    link = (soup.find('div', class_="install")
AttributeError: 'NoneType' object has no attribute 'find'
```

See https://www.rust-lang.org/en-US/other-installers.html

**Comment by LyzardKing** [comment]
Hi, you need the latest version of umake.
You can get it from the ppa listed in the readme

On May 31, 2018 10:52 AM, "Jonas mg" <notifications@github.com> wrote:

$ umake --version
16.11.1
$ umake -vv rust
#(cutting off noise)
DEBUG: Installation path provided. Checking if exists.
DEBUG: Download application provider page
INFO: Start downloading
DownloadItem(url='https://www.rust-lang.org/en-US/downloads.html',
checksum=None, headers=None, ignore_encoding=False, cookies=None) in
memory
DEBUG: Starting new HTTPS connection (1): www.rust-lang.org
DEBUG: https://www.rust-lang.org:443 "GET /en-US/downloads.html HTTP/1.1" 200 91
DEBUG: Deliver download update:
{'https://www.rust-lang.org/en-US/downloads.html': {'current': 0,
'size': 91}} of 91
DEBUG: Deliver download update:
{'https://www.rust-lang.org/en-US/downloads.html': {'current': 91,
'size': 91}} of 91
INFO: https://www.rust-lang.org/en-US/downloads.html download finished
INFO: All pending downloads for
[DownloadItem(url='https://www.rust-lang.org/en-US/downloads.html',
checksum=None, headers=None, ignore_encoding=False, cookies=None)]
done
DEBUG: Fetched download page, parsing.
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/rust.py", line
98, in get_metadata_and_check_license
    link = (soup.find('div', class_="install")
AttributeError: 'NoneType' object has no attribute 'find'

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ubuntu/ubuntu-make/issues/557>, or mute the thread

**Comment by tredoe** [comment]
Thanks!
