### ISSUE TITLE
umake installs Netbeans 8.2

### ISSUE THREAD

**Issue by THUFIR** [ubuntu/ubuntu-make#585]
Netbeans 9+ should install.

Apparently, this is due to:

According to Ubuntu-make's official repository on GitHub last time Netbeans data such as link was updated/committed on 30 March 2017 while Netbeans 9.0 was released on 29 July 2018. So, I believe as of now it is impossible to install Netbeans 9.0 via ubuntu-make until it updates the details. You'll find that all folders here which contain details about Netbeans have details of version 8.2.

https://askubuntu.com/q/1102135/45156

Sure enough, browsing I see:

https://github.com/ubuntu/ubuntu-make/tree/master/tests/data/server-content

which shows:

https://github.com/ubuntu/ubuntu-make/tree/master/tests/data/server-content/download.netbeans.org/netbeans/8.2/final/zip

Is there some rationale for not being at version 9?

**Comment by LyzardKing** [comment]
The file you link to is only for testing purposes. We don't update the tests, since the program is made to download the latest archive from upstream.
We find the url in the known download page using regex mostly.
For example that's why you can download the latest version of eclipse,
even without the program being updated specifically.
In this case the url page changed, because netbeans is now an apache product.
So we probably need to change the url for the download page.
In you look at the source (file umake/frameworks/ide.py),
you can see that we're still pulling from the previous download page (https://netbeans.org/downloads/zip.html)

At the moment I can't work on this, maybe next week.
If you want to try and update this let me know!
Also, thanks for the issue, at least now we know that this needs updating...

**Comment by THUFIR** [comment]
thanks.

**Comment by LyzardKing** [comment]
you need to set the download page (https://netbeans.apache.org/download/)
then in that page set a new_download_url (you can look at the BaseEclipse framework)
I'm available if you need any info

**Comment by LyzardKing** [comment]
Fixed in master
