### ISSUE TITLE
Transition to Arduino IDE snap?

### ISSUE THREAD

**Issue by galgalesh** [ubuntu/ubuntu-make#629]
I took over maintainership of the Arduino IDE snap a few months ago. I deprecated the broken `arduino-mhall119` snap and created a new one: https://snapcraft.io/arduino

Given that ubuntu-make also provides the latest Arduino IDE, I was wondering if there was interest in combining our efforts? Can ubuntu-make integrate with snaps?

**Comment by LyzardKing** [comment]
Hi @galgalesh 
First of all great work on the snap side!
Unfortunately I believe that snaps and umake have different base ideas..
I do believe that umake is not useful if a proper package is being released by upstream (snap or not).
I can see that umake has lost some of its usefulness, since the introduction of snaps (and it's entirely fine, I use and develop snaps as well!)
But the philosophy (and practicality) of the two systems is not the same, so I'd like to keep umake a separate project.
Thanks!

**Comment by galgalesh** [comment]
Ok, thanks for your response.

My eventual goal is to have Arduino maintain the snap upstream, but I thought umake might be a good place to "host" the snap until that happens. But I understand that the two systems are very different, so I'll close this issue.
