### ISSUE TITLE
Add Perl support

### ISSUE THREAD

**Issue by abraxxa** [ubuntu/ubuntu-make#85]
Please also add Perl support via perlbrew/plenv and Padre as IDE.

**Comment by abraxxa** [comment]
Can you please add some info in which commit(s) this was added and maybe a documentation link? Thanks!

**Comment by LyzardKing** [comment]
It hasn't been added yet. This issue was closed but the proposal is still open in the Projects tab.

As far as I can tell the Padre ide has not been updated in a while, perlbrew is a bash command, not a tarfile, and plenv is run directly from the git repo.

If this is the case, but please let me know if I'm missing something, since I'm not familiar with these tools, they are not things we can add to umake.

If there is a newer tool/ide tha is available as a tarfile let me know so we can add it.

**Comment by abraxxa** [comment]
Why does it have to be a tarfile? Can I read up on that simewhere?

**Comment by LyzardKing** [comment]
There's no real documentation for umake (I should write it), but the idea has always been to distribute programs that are available in archives (generally tarfiles), that have version releases.
If you want to understand how it works you can have a look at the android studio, or the ides that are available on umake (you can find the relevant files in the frameworks directory on the repo).

Archives are easier to manage, and we can decompress them in a consistent file structure, and they are "auto-contained" as much as possible (except the dependencies we add through apt of course).
